databases:
  - name: my_database
    databaseName: my_database
    user: my_database

services:
  - type: web
    name: rendsite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn database.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
