# Generated by Django 4.1.4 on 2023-03-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0002_betcode_odd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=255)),
                ('total_odd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ticket_time', models.DateTimeField()),
                ('placed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
