# Generated by Django 4.1.3 on 2022-11-13 13:57

from django.db import migrations, models
import django.db.models.deletion
import training.validators


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/images', validators=[training.validators.validate_file_size])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_image', to='training.course')),
            ],
        ),
    ]
