# Generated by Django 4.1.4 on 2022-12-24 05:36

from django.db import migrations, models
import django.db.models.deletion
import training.validators


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students/images', validators=[training.validators.validate_file_size])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_image', to='training.student')),
            ],
        ),
    ]
