# Generated by Django 4.1.4 on 2022-12-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_studentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentimage',
            old_name='course',
            new_name='student',
        ),
    ]
